---
- hosts: all
  tasks:
    - name: Delete S3 backet
      shell: aws s3api delete-bucket --bucket {{ s3_name }} --region {{ aws_region }}
#     aws_s3:
#      aws_access_key: "{{ access_key }}"
#      aws_secret_key: "{{ secret_key }}"
#       bucket: "{{ s3_name }}-{{ env }} "
#       mode: delete
#       region: "{{ aws_region }}"
    