---

- name: Network Getting Started First Playbook
  hosts: servers
  connection: local
  tasks:
    - aws_s3_bucket_info:
      register: result
    - name: List buckets
      debug:
        msg: "{{ result['buckets'] }}"
#        msg: "{{ result['buckets'][0]['name'] }}"
