---

- name: Network Getting Started First Playbook
  hosts: all
  tasks:
    - name: Display the config
      debug:
        msg: "-----------------env: {{ env }}"
    - aws_s3_bucket_info:
#      region: "ca-central-1"
      register: result

    - name: List buckets
      debug:
        msg: "{{ result['buckets'][0]['name'] }}"