---
  - name: Copy attributes for SQS
    template:
      dest: "/tmp/attributes-queue-{{ sqs_name }}.json"
      src: "attributes-queue.j2"
  
  - name: "Create SQS queue, setup attributes"
    shell: >
       aws sqs create-queue --queue-name {{ sqs_name }}
       --attributes file:///tmp/attributes-queue-{{ sqs_name }}.json
       --region {{ aws_region }}