---
# Create a simple s3 bucket
- name: Create an empty bucket
  aws_s3:
#    aws_access_key: "{{ access_key }}"
#    aws_secret_key: "{{ secret_key }}"
    bucket: "{{ s3_name }}-{{ env }}"
    mode: create
    permission: 
     - private
#    region: eu-west-1
