---
- name: Create an empty S3 bucket
  shell: >
     aws s3api create-bucket 
     --bucket {{ s3_name }} 
     --region {{ aws_region }} 
     --create-bucket-configuration LocationConstraint={{ aws_region }}

- name: Configure an empty S3 bucket
  shell: >
     aws s3api put-public-access-block 
     --bucket {{ s3_name }}
     --public-access-block-configuration "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"

- name: Configure policy for S3
  template:
    dest: "/tmp/{{ s3_name }}.json"
    src: "policy.j2"

- name: Set policy to S3 bucket
  shell: >
    aws s3api put-bucket-policy 
    --bucket {{ s3_name }} 
    --policy file:///tmp/{{ s3_name }}.json
    
- name: Delete S3 file policy JSON
  file:
    path: /tmp/{{ s3_name }}.json
    state: absent